/* 
 * Manage Contractors APIs
 *
 * This API supports all services required to manage Employees on HR system
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Employee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmployeeTests
    {
        // TODO uncomment below to declare an instance variable for Employee
        //private Employee instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Employee
            //instance = new Employee();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Employee
        /// </summary>
        [Test]
        public void EmployeeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Employee
            //Assert.IsInstanceOfType<Employee> (instance, "variable 'instance' is a Employee");
        }


        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Test]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Test]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
        /// <summary>
        /// Test the property 'FamilyName'
        /// </summary>
        [Test]
        public void FamilyNameTest()
        {
            // TODO unit test for the property 'FamilyName'
        }
        /// <summary>
        /// Test the property 'Formatted'
        /// </summary>
        [Test]
        public void FormattedTest()
        {
            // TODO unit test for the property 'Formatted'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'GivenName'
        /// </summary>
        [Test]
        public void GivenNameTest()
        {
            // TODO unit test for the property 'GivenName'
        }
        /// <summary>
        /// Test the property 'HouseName'
        /// </summary>
        [Test]
        public void HouseNameTest()
        {
            // TODO unit test for the property 'HouseName'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Test]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }
        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Test]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Test]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'PreferredUsername'
        /// </summary>
        [Test]
        public void PreferredUsernameTest()
        {
            // TODO unit test for the property 'PreferredUsername'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'StreetAddress'
        /// </summary>
        [Test]
        public void StreetAddressTest()
        {
            // TODO unit test for the property 'StreetAddress'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Test]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'Zoneinfo'
        /// </summary>
        [Test]
        public void ZoneinfoTest()
        {
            // TODO unit test for the property 'Zoneinfo'
        }

    }

}
